# Generated by Django 2.1.7 on 2019-03-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified_user',
            field=models.BooleanField(default=False),
        ),
    ]
