# Generated by Django 2.1.7 on 2019-03-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_verified_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verified_user',
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
