# Generated by Django 2.1.7 on 2019-05-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastRequestHour', models.IntegerField(default=0)),
                ('lastRequestMinute', models.IntegerField(default=0)),
                ('remainingRequests', models.IntegerField()),
                ('usedRequests', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameTime', models.CharField(max_length=100)),
                ('gameDate', models.CharField(max_length=100)),
                ('homeTeam', models.CharField(max_length=100)),
                ('awayTeam', models.CharField(max_length=100)),
                ('betType', models.CharField(max_length=100)),
                ('eventID', models.CharField(max_length=100)),
                ('homeOdds', models.FloatField()),
                ('awayOdds', models.FloatField()),
                ('drawOdds', models.FloatField()),
            ],
        ),
    ]
